sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    CACHE_IMAGE: ml4ailab/automates

before_install:
  - docker pull $CACHE_IMAGE:latest
  - CI_ENV=`bash <(curl -s https://codecov.io/env)`
  - docker run $CI_ENV -itd --rm --name build-con $CACHE_IMAGE:latest

script:
  - docker exec build-con git fetch
  - docker exec build-con git checkout $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker exec build-con git pull; fi
  - if [[ ! $TRAVIS_PULL_REQUEST_BRANCH == "" ]]; then docker exec build-con git pull origin $TRAVIS_PULL_REQUEST_BRANCH; fi
  - docker exec build-con make test
  - docker exec --workdir /automates/docs build-con make apidocs
  - docker exec --workdir /automates/docs build-con make html
  - docker cp build-con:/automates/docs .
  - docker exec -e CODECOV_TOKEN=$CODECOV_TOKEN build-con bash -c 'bash <(curl -s https://codecov.io/bash)'

deploy:
  local-dir: docs/_build/html
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
