vars: org/clulab/aske_automates/grammars/vars.yml

rules:


  ####VALUES####


  - name: var_equals_val
    label: ParameterSetting
    priority: ${priority}
    type: token
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      # @trigger:Concept "=" @Value:Value
      (@variable:Variable|@variable:Concept) (?<trigger> [word="="]) @value:Value


  - name: var-vary_between
    label: IntervalParameterSetting
    priority: ${priority}
    type: dependency
    example: "The value of Kcbmax was varied between 0.9 and 1.4"
    pattern: |
      trigger = [lemma='vary']
      variable:Variable = nsubjpass nmod_of
      value:Interval = nmod_between

#
  - name: var-vary_between_symbols_interval
    label: IntervalParameterSetting
    priority: ${priority}
    type: token
    example: "Kcbmax with the ETo-Kcb method had little influence on maize and cotton yield for 0.9 < Kcbmax < 1.15"
    pattern: |
      @valueLeast:Value [word = "<"] (?<trigger> @Variable) [word = "<"] @valueMost:Value
#

  - name: var-more_than_symbol
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "but simulated yield decreased rapidly for Kcbmax > 1.15 (fig. 6a)."
    pattern: |
      trigger = [lemma='>']
      variable:Concept = <advmod <nummod
      value:Value = <advmod [tag = "CD"]


  - name: var-less_than_symbol
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "but simulated yield decreased rapidly for Kcbmax < 1.15 (fig. 6a)."
    pattern: |
      trigger = [lemma='<']
      variable:Concept = <dep <nummod <dep | <advmod <nummod
      value:Value = </dep|advmod/ [tag = "CD"]

  - name: var_hard-coded
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "EORATIO for maize simulations was hard-coded to 1.0 within DSSAT-CSM."
    pattern: |
      trigger = [word=/(?i)^hard-coded/]
      variable:Concept = nsubj
      value: Concept = /nmod_to/


  - name: var-noun_of_param
    label: IntervalParameterSetting
    priority: ${priority}
    type: token
    example: "If E and T data are unavailable, values of SKc from 0.5 to 0.7 are recommended."
    pattern: |
      (?<trigger> [lemma="value"]) of @variable:Variable from @valueLeast:Value to @valueMost:Value


  - name: var-noun_of1
    label: ParameterSetting
    priority: ${priority}
    type: token
    example: "With an RMSE of 22.8%, drastic discrepancies were found in the comparison of Ref-ET ETo and ETpm from DSSAT-CSM version 4.5 for Arizona conditions."
    pattern: |
      /(?i)with/ (an|a|the) @variable:Variable of @value:Value

