vars: org/clulab/aske_automates/grammars/vars.yml

rules:


  ####VALUES####


  - name: var_equals_val
    label: ParameterSetting
    priority: ${priority}
    type: token
    example: "EORATIO is defined as the maximum Kcs at LAI = 6.0"
    pattern: |
      # @trigger:Concept "=" @Value:Value
      (@variable:Variable|@variable:Concept) (?<trigger> [word="="]) @value:Value


  - name: var-vary_between
    label: IntervalParameterSetting
    priority: ${priority}
    type: dependency
    example: "The value of Kcbmax was varied between 0.9 and 1.4"
    pattern: |
      trigger = [lemma='vary']
      variable:Variable = nsubjpass nmod_of
      valueLeast:Value = nmod_between
      valueMost:Value = nmod_between conj_and

  - name: var_ranges
    label: IntervalParameterSetting
    priority: ${priority}
    type: dependency
    example: "where KEP (typically ranging from 0.5 to 0.8) is defined as an energy extinction coefficient of the canopy for total solar irradiance"
    pattern: |
      trigger = [lemma='range']
      variable:Variable = nsubj
      valueLeast:Value = nmod_from
      valueMost:Value = nmod_from nmod

#
  - name: var-vary_between_symbols_interval
    label: IntervalParameterSetting
    priority: ${priority}
    type: token
    example: "Kcbmax with the ETo-Kcb method had little influence on maize and cotton yield for 0.9 < Kcbmax < 1.15"
    pattern: |
      @valueLeast:Value [word = "<"] (?<trigger> @Variable) [word = "<"] @valueMost:Value
#

  - name: var-more_than_symbol
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "but simulated yield decreased rapidly for Kcbmax > 1.15 (fig. 6a)."
    pattern: |
      trigger = [lemma='>']
      variable:Concept = <advmod <nummod
      value:Value = <advmod [tag = "CD"]


  - name: var-less_than_symbol
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "but simulated yield decreased rapidly for Kcbmax < 1.15 (fig. 6a)."
    pattern: |
      trigger = [lemma='<']
      variable:Concept = <dep <nummod <dep | <advmod <nummod
      value:Value = </dep|advmod/ [tag = "CD"]

  - name: var_hard-coded
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "EORATIO for maize simulations was hard-coded to 1.0 within DSSAT-CSM."
    pattern: |
      trigger = [word=/(?i)^hard-coded/]
      variable:Concept = nsubj
      value:Value = /nmod_to/


  - name: var_taken_as
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "The density of water (Ïw) is taken as 1.0 Mg m-3."
    pattern: |
      trigger = [word=/(?i)^taken/]
      variable:Variable = nsubjpass nmod_of appos
      value:Value = nmod_as nummod
      #todo: combine with a different verb-trigger-based rule


  - name: var-noun_of_param
    label: IntervalParameterSetting
    priority: ${priority}
    type: token
    example: "If E and T data are unavailable, values of SKc from 0.5 to 0.7 are recommended."
    pattern: |
      (?<trigger> [lemma="value"]) of @variable:Variable from @valueLeast:Value to @valueMost:Value


  - name: var-noun_of1
    label: ParameterSetting
    priority: ${priority}
    type: token
    example: "With an RMSE of 22.8%, drastic discrepancies were found in the comparison of Ref-ET ETo and ETpm from DSSAT-CSM version 4.5 for Arizona conditions."
    pattern: |
      /(?i)with/ (an|a|the) @variable:Variable of @value:Value

  - name: var-noun_of2
    label: ParameterSetting
    priority: ${priority}
    example: "In 2014, the authors linked the problem to a misspecification of the equation used to adjust wind speed measurements to a standard height of 2.0 m"
    pattern: |
      trigger = [word = "standard" & tag = "JJ"]
      variable: Concept = <amod <nmod_to dobj
      value: Concept = <amod nmod_of nummod [entity = "NUMBER"]

  #fixme: could result in false positives, but does not seem to work when limit to [word = DOY]
  - name: var-DOY
    label: ParameterSetting
    priority: ${priority}
    type: token
    example: "As canopy cover increased with vegetative growth, the transpiration portion exceeded the evaporation portion of ET, beginning around DOY 165 for maize and DOY 175 for cotton."
    pattern: |
      @variable:Variable @value:Value

  - name: adjust_to_setting
    label: ParameterSetting
    priority: ${priority}
    type: dependency
    example: "In 2014, the authors linked the problem to a misspecification of the equation used to adjust wind speed measurements to a standard height of 2.0 m"
    pattern: |
      trigger = [word=/(?i)adjust/]
      variable:Concept = dobj
      value:Value = nmod_to nmod_of nummod